"""ai_service — ALL Claude calls live here (spec §6.3).

Four responsibilities, each a well-defined function with a strict output
schema. Live-provider output is parsed defensively (code fences stripped,
JSON validated).

Fallback policy differs by criticality, and by environment:

* **Employee-facing content** (training modules, threat explanations) must
  never be silently substituted in production — a customer would receive
  canned copy written for a fictional company, presented as training derived
  from *their* threat. Outside the demo build a provider failure raises
  ``AIUnavailable`` and fails the loop stage, which is visible and retryable.
* **Analyst assistance** (triage notes, executive briefing) is advisory and
  clearly labelled, so a mock fallback there degrades gracefully rather than
  blocking an employee from reporting a live phish.

Every generated module records which engine actually produced it
(``generation_source``), so provenance is never inferred.
"""
import json
import logging
import re
from typing import Any

from ..config import get_settings
from .providers import AnthropicProvider, MockAIProvider

logger = logging.getLogger("cyclowareness.ai")

_provider = None
_mock = MockAIProvider()


def get_provider():
    global _provider
    if _provider is None:
        settings = get_settings()
        if settings.anthropic_api_key:
            _provider = AnthropicProvider()
            logger.info("AI provider: Anthropic (%s)", settings.ai_model)
        else:
            _provider = _mock
            logger.info("AI provider: MockAIProvider (no ANTHROPIC_API_KEY set)")
    return _provider


def _parse_json(raw: str) -> Any:
    """Parse a JSON-only response defensively: strip code fences and prose."""
    text = raw.strip()
    text = re.sub(r"^```(?:json)?\s*", "", text)
    text = re.sub(r"\s*```$", "", text)
    start = text.find("{")
    end = text.rfind("}")
    if start == -1 or end == -1:
        raise ValueError("No JSON object found in AI response")
    return json.loads(text[start : end + 1])


# --- schema validation --------------------------------------------------------

def _validate_training(data: dict) -> dict:
    for key in ("title", "description", "content", "quiz", "takeaway"):
        if key not in data:
            raise ValueError(f"Training module missing key: {key}")
    if not isinstance(data["content"], list) or not (2 <= len(data["content"]) <= 6):
        raise ValueError("Training content must be 2–6 sections")
    for section in data["content"]:
        if "heading" not in section or "body" not in section:
            raise ValueError("Each content section needs heading and body")
    if not isinstance(data["quiz"], list) or not (3 <= len(data["quiz"]) <= 5):
        raise ValueError("Quiz must have 3–5 questions")
    for q in data["quiz"]:
        if not all(k in q for k in ("question", "options", "correct_index")):
            raise ValueError("Malformed quiz question")
        if len(q["options"]) != 4 or not (0 <= int(q["correct_index"]) <= 3):
            raise ValueError("Each question needs exactly 4 options and a valid correct_index")
        q.setdefault("explanation", "")
    data.setdefault("channel", "email")
    data.setdefault("est_minutes", 3)
    data["est_minutes"] = int(data["est_minutes"])
    return data


def _validate_triage(data: dict) -> dict:
    data.setdefault("summary", "")
    data.setdefault("suspicion_level", "medium")
    data.setdefault("indicators", [])
    data.setdefault("likely_iocs", {"urls": [], "domains": [], "sender_patterns": []})
    data.setdefault("recommended_action", "")
    if data["suspicion_level"] not in ("high", "medium", "low"):
        data["suspicion_level"] = "medium"
    return data


# --- provenance ------------------------------------------------------------------
# Which engine actually produced a given piece of content. This is persisted on
# the TrainingModule and shown to the analyst: content generated by the offline
# mock must never be presentable as bespoke, threat-derived AI output.

SOURCE_ANTHROPIC = "anthropic"
SOURCE_MOCK = "mock"


class AIUnavailable(RuntimeError):
    """The configured live provider failed and no honest fallback is permitted."""


def _fallback_allowed() -> bool:
    """Silently substituting canned demo content is a demo affordance only.

    In production a customer would receive hardcoded copy written for a
    fictional company, labelled as training generated from *their* threat.
    Better to fail the loop stage — it is visible, retryable, and honest.
    """
    return get_settings().is_demo


# --- the four responsibilities -------------------------------------------------

async def generate_training(analysis: dict[str, Any]) -> tuple[dict[str, Any], str]:
    """Threat → personalized micro-training module.

    Returns ``(module, generation_source)`` so callers can persist which engine
    actually produced the content.
    """
    provider = get_provider()
    is_live = provider is not _mock
    try:
        raw = await provider.complete("training_generation", analysis)
        return _validate_training(_parse_json(raw)), (SOURCE_ANTHROPIC if is_live else SOURCE_MOCK)
    except Exception as exc:
        if not is_live:
            raise
        if not _fallback_allowed():
            logger.exception("Live AI training generation failed; refusing to substitute mock content")
            raise AIUnavailable(
                "The AI provider failed and mock substitution is disabled outside the demo build. "
                "Retry the run once the provider recovers."
            ) from exc
        logger.exception("Live AI training generation failed; falling back to mock (demo build)")
        raw = await _mock.complete("training_generation", analysis)
        return _validate_training(_parse_json(raw)), SOURCE_MOCK


async def explain_threat(analysis: dict[str, Any]) -> str:
    """Technical verdict → plain-language explanation for non-technical staff."""
    provider = get_provider()
    is_live = provider is not _mock
    try:
        text = (await provider.complete("threat_explanation", analysis)).strip()
        if not text:
            raise ValueError("Empty explanation")
        return text
    except Exception as exc:
        if not is_live:
            raise
        if not _fallback_allowed():
            logger.exception("Live AI explanation failed; refusing to substitute mock content")
            raise AIUnavailable("The AI provider failed while writing the threat explanation.") from exc
        logger.exception("Live AI explanation failed; falling back to mock (demo build)")
        return (await _mock.complete("threat_explanation", analysis)).strip()


async def triage_assist(report: dict[str, Any]) -> dict[str, Any]:
    """Reported email → why it's suspicious + likely IOCs (analyst accelerator).

    Advisory only, and always reviewed by a human before it changes anything —
    so a heuristic fallback is preferable to blocking an employee from
    reporting a live phish. The mock here is a real keyword/IOC extractor, not
    canned prose, so a degraded triage note is still genuinely useful.
    """
    provider = get_provider()
    try:
        raw = await provider.complete("triage_assist", report)
        return _validate_triage(_parse_json(raw))
    except Exception:
        if provider is _mock:
            raise
        logger.exception("Live AI triage failed; falling back to heuristic triage")
        raw = await _mock.complete("triage_assist", report)
        return _validate_triage(_parse_json(raw))


async def executive_briefing(metrics: dict[str, Any]) -> str:
    """Org risk posture → natural-language executive summary."""
    provider = get_provider()
    try:
        text = (await provider.complete("executive_briefing", metrics)).strip()
        if not text:
            raise ValueError("Empty briefing")
        return text
    except Exception:
        if provider is _mock:
            raise
        logger.exception("Live AI briefing failed; falling back to mock")
        return (await _mock.complete("executive_briefing", metrics)).strip()
