"""Migrations, and the upgrade path that used to lose columns silently.

Every test here runs against its OWN throwaway database, built with a second
engine — never the session-wide one the rest of the suite shares. Running a
migration against that would rebuild the schema out from under every other test.

The scenario these exist for: `create_all()` CREATES a table it has never seen
and does nothing to one it has. Swapping in the vendored sandbox engine added
nine columns to `sandbox_jobs`, so on any existing database the release reported
success and left them missing — `/api/health` answering 200 while every sandbox
query raised `no such column: sandbox_jobs.tenant_id`.
"""
from __future__ import annotations

import ast
import os
import pathlib
import re
import subprocess
import sys
from datetime import datetime, timezone

import pytest
from alembic import command
from alembic.config import Config
from sqlalchemy import create_engine, inspect, text

from app.database import (
    _ADOPTION_LADDER,
    BASELINE_REVISION,
    SANDBOX_ENGINE_REVISION,
    UnadoptableDatabase,
    _legacy_stamp_target,
    alembic_config,
)

#: The nine columns the sandbox engine integration added. If a future revision
#: adds more, this list is not what needs updating — the adoption ladder in
#: app/database.py is.
INTEGRATION_COLUMNS = {
    "tenant_id", "submitted_by", "dynamic", "sample_deleted_at", "impact",
    "verdict", "mitre", "first_completed_at", "engine_manifest",
}

#: What the pre-integration table carried instead, and what moved to
#: `sandbox_job_links` rather than being deleted.
MOVED_COLUMNS = {"loop_run_id", "submitted_by_user_id"}


@pytest.fixture
def scratch(tmp_path):
    """A private database and an Alembic config pointed at it."""
    url = f"sqlite:///{tmp_path / 'scratch.db'}"
    eng = create_engine(url)

    def config_at() -> Config:
        cfg = alembic_config()
        cfg.set_main_option("sqlalchemy.url", url)
        return cfg

    def upgrade(target: str) -> None:
        cfg = config_at()
        with eng.begin() as conn:
            cfg.attributes["connection"] = conn
            command.upgrade(cfg, target)

    def stamp(target: str) -> None:
        cfg = config_at()
        with eng.begin() as conn:
            cfg.attributes["connection"] = conn
            command.stamp(cfg, target)

    def columns(table: str) -> set[str]:
        with eng.connect() as conn:
            return {c["name"] for c in inspect(conn).get_columns(table)}

    def tables() -> set[str]:
        with eng.connect() as conn:
            return set(inspect(conn).get_table_names())

    eng.upgrade = upgrade          # type: ignore[attr-defined]
    eng.stamp = stamp              # type: ignore[attr-defined]
    eng.columns = columns          # type: ignore[attr-defined]
    eng.tables = tables            # type: ignore[attr-defined]
    yield eng
    eng.dispose()


def _seed_pre_integration(eng) -> None:
    """One sandbox job with both associations set, as a running deployment has."""
    now = datetime.now(timezone.utc).isoformat(" ")
    with eng.begin() as conn:
        conn.execute(text(
            "INSERT INTO users (id,email,hashed_password,role) "
            "VALUES (7,'analyst@example.test','x','analyst')"
        ))
        conn.execute(text(
            "INSERT INTO threats (id,source,artifact_type,artifact_ref,artifact_meta,title,created_at)"
            " VALUES (1,'inbox','file','ref','{}','t',:now)"
        ), {"now": now})
        conn.execute(text(
            "INSERT INTO loop_runs (id,trigger_threat_id,current_stage,status,stage_history,"
            "targeting,created_at) VALUES (3,1,'feedback','completed','[]','{}',:now)"
        ), {"now": now})
        conn.execute(text(
            "INSERT INTO sandbox_jobs (id,public_id,source,submitted_by_user_id,original_name,"
            "sha256,md5,size_bytes,mime,magic,family,extension_mismatch,status,stage,tiers,"
            "analysis,iocs,score_breakdown,rule_score,ai_score,final_score,risk_level,"
            "loop_run_id,created_at) VALUES (1,'aaaaaaaa-1111-1111-1111-111111111111','loop',7,"
            "'invoice.ps1','abc','def',146,'text/x-powershell','','script',0,'completed',"
            "'complete','{}','{}','{}','{}',100.0,25.1,70.0,'high',3,:now)"
        ), {"now": now})


def test_the_chain_builds_a_schema_that_matches_the_models(scratch):
    """`alembic check` on a freshly migrated database must find nothing.

    This is the property that lets the rest of the suite keep using
    `create_all()`: the models and the migrations describe the same schema, so a
    test that passes against the models passes against a migrated database.
    """
    scratch.upgrade("head")
    cfg = alembic_config()
    cfg.set_main_option("sqlalchemy.url", str(scratch.url))
    with scratch.begin() as conn:
        cfg.attributes["connection"] = conn
        command.check(cfg)  # raises AutogenerateDiffsDetected on drift


def test_no_table_references_one_that_does_not_exist_yet(tmp_path):
    """PostgreSQL validates a foreign key target at CREATE time. SQLite does not.

    So a baseline that creates `sandbox_jobs` (which references `loop_runs`)
    before `loop_runs` passes every local run and dies on the first PostgreSQL
    one with `relation "loop_runs" does not exist`. That is exactly what
    happened, and this test is why it cannot happen twice — it reads the
    PostgreSQL DDL that Alembic *renders*, so it catches the ordering without
    needing a PostgreSQL server.
    """
    sql = subprocess.run(
        [sys.executable, "-m", "alembic", "upgrade", "head", "--sql"],
        cwd=str(pathlib.Path(__file__).resolve().parents[1]),
        env={
            **os.environ,
            "DATABASE_URL": "postgresql+psycopg://u:p@localhost/db",
            "APP_ENV": "demo",
        },
        capture_output=True, text=True, check=True,
    ).stdout

    created: list[str] = []
    problems: list[str] = []
    for statement in sql.split(";"):
        match = re.search(r"CREATE TABLE (\w+)", statement)
        if not match:
            continue
        name = match.group(1)
        for target in re.findall(r"REFERENCES (\w+)", statement):
            if target != name and target not in created:
                problems.append(f"{name} REFERENCES {target} before it is created")
        created.append(name)

    assert created, "rendered no DDL at all — the check would pass vacuously"
    assert not problems, "; ".join(problems)


#: SQL that means different things on SQLite and PostgreSQL. Each entry is a
#: mistake this chain has actually made, or the direct sibling of one.
_DIALECT_TRAPS = (
    (
        r"\bMAX\s*\([^)]*,",
        "two-argument MAX is scalar on SQLite and an AGGREGATE on PostgreSQL — use CASE",
    ),
    (
        r"\bMIN\s*\([^)]*,",
        "two-argument MIN is scalar on SQLite and an AGGREGATE on PostgreSQL — use CASE",
    ),
    (
        r"\bGREATEST\s*\(|\bLEAST\s*\(",
        "GREATEST/LEAST do not exist on SQLite — use CASE",
    ),
    (
        r"server_default\s*=\s*[\"']\s*[\[{]",
        "a text server_default on a JSON column is refused by PostgreSQL — "
        "add nullable, backfill, then SET NOT NULL",
    ),
    (
        r"\bIFNULL\s*\(",
        "IFNULL is SQLite-only — use COALESCE",
    ),
    (
        r"\bdatetime\s*\(\s*'now'",
        "datetime('now') is SQLite-only — use CURRENT_TIMESTAMP or pass the value in",
    ),
)


def test_no_migration_uses_sql_that_means_something_different_on_postgresql():
    """The suite runs on SQLite; production runs on PostgreSQL.

    Every trap listed here has cost this chain a red build or would have: SQLite
    accepts the statement, PostgreSQL rejects it or — worse — reads it
    differently. Rendering the DDL is not enough to catch them, because
    `--sql` renders happily and only execution fails, so this reads the
    migration source instead.
    """
    versions = pathlib.Path(__file__).resolve().parents[1] / "migrations" / "versions"
    files = sorted(versions.glob("*.py"))
    assert files, "no migrations found — the check would pass vacuously"

    problems = []
    for path in files:
        source = path.read_text(encoding="utf-8")

        # Strip the MODULE DOCSTRING AND COMMENTS ONLY — never every triple-quoted
        # string. These traps are discussed in the very migrations that avoid
        # them, so an explanation must not read as an occurrence; but the SQL
        # lives inside `op.execute("""...""")`, so a blanket `"""..."""` strip
        # deletes exactly what this test exists to read. It did, and the test
        # passed on an injected `MAX(0.0, ...)` — vacuous and worse than absent.
        tree = ast.parse(source)
        body = source
        if (doc := ast.get_docstring(tree, clean=False)) is not None:
            body = body.replace(f'"""{doc}"""', "", 1)
        body = re.sub(r"^\s*#.*$", "", body, flags=re.MULTILINE)
        for pattern, why in _DIALECT_TRAPS:
            for match in re.finditer(pattern, body, re.IGNORECASE):
                line = body[: match.start()].count("\n") + 1
                problems.append(f"{path.name}:~{line}: {match.group(0)!r} — {why}")
    assert not problems, "\n".join(problems)


def test_the_downgrade_is_the_exact_reverse_of_the_upgrade(tmp_path):
    """Dropping a table still referenced by another fails on PostgreSQL.

    The upgrade order is checked above; this is its mirror. Getting it wrong
    breaks `alembic downgrade`, which is the only thing standing between a bad
    release and a restore from backup.
    """
    baseline = next(
        p for p in (pathlib.Path(__file__).resolve().parents[1] / "migrations" / "versions").glob("*.py")
        if "0001" in p.name
    )
    src = baseline.read_text(encoding="utf-8")
    up = src[src.index("def upgrade"):src.index("def downgrade")]
    down = src[src.index("def downgrade"):]
    created = re.findall(r"op\.create_table\('([a-z_]+)'", up)
    dropped = re.findall(r"op\.drop_table\('([a-z_]+)'", down)
    assert created, "no tables parsed — the check would pass vacuously"
    assert dropped == list(reversed(created))


def test_the_baseline_is_the_pre_integration_shape(scratch):
    """0001 must NOT already contain the integration.

    If it did, there would be no revision that adds those columns, and an
    existing database could never be repaired — which is the whole reason the
    baseline was split.
    """
    scratch.upgrade(BASELINE_REVISION)
    columns = scratch.columns("sandbox_jobs")
    assert not (INTEGRATION_COLUMNS & columns), "baseline already has the integration"
    assert MOVED_COLUMNS <= columns
    assert "sandbox_job_links" not in scratch.tables()


def test_upgrading_a_pre_integration_database_adds_the_nine_missing_columns(scratch):
    """The exact failure this migration exists for."""
    scratch.upgrade(BASELINE_REVISION)
    _seed_pre_integration(scratch)
    scratch.upgrade("head")

    columns = scratch.columns("sandbox_jobs")
    assert INTEGRATION_COLUMNS <= columns
    assert not (MOVED_COLUMNS & columns), "the moved columns should be gone from the job"

    with scratch.connect() as conn:
        row = conn.execute(text(
            "SELECT final_score, risk_level, tenant_id, verdict, mitre FROM sandbox_jobs WHERE id=1"
        )).one()
    # The row survived the rebuild, and the new columns carry their defaults
    # rather than NULL in a NOT NULL column.
    assert row.final_score == pytest.approx(70.0)
    assert row.risk_level == "high"
    assert row.tenant_id == "default"
    assert row.verdict == "{}"
    assert row.mitre == "[]"


def test_the_association_moves_to_the_link_table_rather_than_being_dropped(scratch):
    """`loop_run_id` and `submitted_by_user_id` leave the job but not the database.

    The engine may not carry a foreign key into `users` or `loop_runs` — the
    standalone product has neither table — so the portal keeps the association
    on its own side of the seam. Losing it would silently orphan every job the
    awareness loop had raised.
    """
    scratch.upgrade(BASELINE_REVISION)
    _seed_pre_integration(scratch)
    scratch.upgrade("head")

    with scratch.connect() as conn:
        link = conn.execute(text(
            "SELECT job_id, loop_run_id, submitted_by_user_id FROM sandbox_job_links"
        )).one()
    assert (link.job_id, link.loop_run_id, link.submitted_by_user_id) == (1, 3, 7)


def test_a_job_with_no_association_gets_no_link_row(scratch):
    """Absence is not an error — it is a job the portal has nothing to add to."""
    scratch.upgrade(BASELINE_REVISION)
    now = datetime.now(timezone.utc).isoformat(" ")
    with scratch.begin() as conn:
        conn.execute(text(
            "INSERT INTO sandbox_jobs (id,public_id,source,original_name,sha256,md5,size_bytes,"
            "mime,magic,family,extension_mismatch,status,stage,tiers,analysis,iocs,score_breakdown,"
            "rule_score,ai_score,final_score,risk_level,created_at) VALUES (9,"
            "'cccccccc-3333-3333-3333-333333333333','upload','x.txt','a','b',1,'text/plain','',"
            "'script',0,'completed','complete','{}','{}','{}','{}',0,0,1.7,'low',:now)"
        ), {"now": now})
    scratch.upgrade("head")
    with scratch.connect() as conn:
        assert conn.execute(text("SELECT count(*) FROM sandbox_job_links")).scalar_one() == 0


# --- the adoption ladder ------------------------------------------------------
def test_a_create_all_database_is_stamped_at_the_revision_it_matches(scratch):
    """No `alembic_version`, but the tables are there. `upgrade head` alone would
    try to CREATE what exists and abort the boot."""
    scratch.upgrade(BASELINE_REVISION)
    with scratch.begin() as conn:
        conn.execute(text("DROP TABLE alembic_version"))
    with scratch.connect() as conn:
        assert _legacy_stamp_target(conn) == BASELINE_REVISION


def test_a_database_at_head_is_stamped_at_head(scratch):
    """Stamping it lower would re-run a migration and re-add existing columns.

    Asserted against the NEWEST rung, not a fixed revision: as the ladder grows,
    a database carrying every marker is at the top of it. Pinning this to
    `0002_sandbox_engine` was already wrong the day 0003 landed.
    """
    scratch.upgrade("head")
    with scratch.begin() as conn:
        conn.execute(text("DROP TABLE alembic_version"))
    newest = _ADOPTION_LADDER[0][0]
    with scratch.connect() as conn:
        assert _legacy_stamp_target(conn) == newest


def test_an_empty_database_is_not_adopted(scratch):
    """Nothing to adopt — the migrations build it from nothing."""
    with scratch.connect() as conn:
        assert _legacy_stamp_target(conn) is None


def test_a_database_alembic_already_manages_is_not_re_stamped(scratch):
    scratch.upgrade("head")
    with scratch.connect() as conn:
        assert _legacy_stamp_target(conn) is None


def test_an_undatable_database_is_refused_rather_than_guessed_at(scratch):
    """Tables, but nothing to date them by.

    Stamping a revision that does not match tells Alembic a migration has run
    when it has not, and the next upgrade then alters columns that are not
    there — corruption rather than a clean failure. Refusing is the only safe
    answer, and it names what it found.
    """
    with scratch.begin() as conn:
        conn.execute(text("CREATE TABLE something_else (id INTEGER PRIMARY KEY)"))
    with scratch.connect() as conn:
        with pytest.raises(UnadoptableDatabase) as caught:
            _legacy_stamp_target(conn)
    assert "something_else" in str(caught.value)


def test_the_ladder_has_a_rung_for_every_revision_that_adds_a_column():
    """A migration that adds a column without adding a rung is a boot failure.

    A pre-Alembic database gets stamped too low, the next upgrade re-adds a
    column that already exists, and the service does not come up. Nothing else
    catches it, because a fresh database never walks that path.

    THIS TEST USED TO CHECK `sandbox_jobs` ONLY, and that is exactly how 0003
    shipped broken: it adds columns to `employees`, the ladder was keyed on
    `sandbox_jobs`, so every database was dated at 0002 and the boot died with
    `duplicate column name: behaviour_risk`. A narrow guard reads as a guard.
    """
    from app.database import _ADOPTION_LADDER

    rungs = {rev for rev, _markers in _ADOPTION_LADDER}
    versions = pathlib.Path(__file__).resolve().parents[1] / "migrations" / "versions"
    files = sorted(versions.glob("*.py"))
    assert files, "no migrations found — the check would pass vacuously"

    adding = {}
    for path in files:
        source = path.read_text(encoding="utf-8")
        revision = None
        for line in source.splitlines():
            if line.startswith("revision = "):
                revision = line.split("=", 1)[1].strip().strip("\"'")
                break
        if not revision or revision == BASELINE_REVISION:
            continue
        # Which tables this revision adds columns to: the table named by the
        # enclosing batch_alter_table for each add_column call.
        tables = set()
        current = None
        for line in source.splitlines():
            match = re.search(r"batch_alter_table\(\s*[\"']([a-z_]+)[\"']", line)
            if match:
                current = match.group(1)
            if "add_column(" in line and current:
                tables.add(current)
        if tables:
            adding[revision] = tables

    assert adding, "parsed no column-adding revisions — the check would pass vacuously"
    missing = {rev: sorted(t) for rev, t in adding.items() if rev not in rungs}
    assert not missing, (
        "these revisions add columns but have no rung in _ADOPTION_LADDER, so a "
        f"pre-Alembic database will be stamped too low and fail to boot: {missing}"
    )

    # And each rung must name a table that revision actually touched, or the
    # marker can never match and the rung is decoration.
    for revision, markers in _ADOPTION_LADDER:
        if revision in adding:
            unmatched = set(markers) - adding[revision]
            assert not unmatched, (
                f"{revision} has rung markers for tables it does not add columns to: {unmatched}"
            )
