"""Migrations, and the upgrade path that used to lose columns silently.

Every test here runs against its OWN throwaway database, built with a second
engine — never the session-wide one the rest of the suite shares. Running a
migration against that would rebuild the schema out from under every other test.

The scenario these exist for: `create_all()` CREATES a table it has never seen
and does nothing to one it has. Swapping in the vendored sandbox engine added
nine columns to `sandbox_jobs`, so on any existing database the release reported
success and left them missing — `/api/health` answering 200 while every sandbox
query raised `no such column: sandbox_jobs.tenant_id`.
"""
from __future__ import annotations

from datetime import datetime, timezone

import pytest
from alembic import command
from alembic.config import Config
from sqlalchemy import create_engine, inspect, text

from app.database import (
    BASELINE_REVISION,
    SANDBOX_ENGINE_REVISION,
    UnadoptableDatabase,
    _legacy_stamp_target,
    alembic_config,
)

#: The nine columns the sandbox engine integration added. If a future revision
#: adds more, this list is not what needs updating — the adoption ladder in
#: app/database.py is.
INTEGRATION_COLUMNS = {
    "tenant_id", "submitted_by", "dynamic", "sample_deleted_at", "impact",
    "verdict", "mitre", "first_completed_at", "engine_manifest",
}

#: What the pre-integration table carried instead, and what moved to
#: `sandbox_job_links` rather than being deleted.
MOVED_COLUMNS = {"loop_run_id", "submitted_by_user_id"}


@pytest.fixture
def scratch(tmp_path):
    """A private database and an Alembic config pointed at it."""
    url = f"sqlite:///{tmp_path / 'scratch.db'}"
    eng = create_engine(url)

    def config_at() -> Config:
        cfg = alembic_config()
        cfg.set_main_option("sqlalchemy.url", url)
        return cfg

    def upgrade(target: str) -> None:
        cfg = config_at()
        with eng.begin() as conn:
            cfg.attributes["connection"] = conn
            command.upgrade(cfg, target)

    def stamp(target: str) -> None:
        cfg = config_at()
        with eng.begin() as conn:
            cfg.attributes["connection"] = conn
            command.stamp(cfg, target)

    def columns(table: str) -> set[str]:
        with eng.connect() as conn:
            return {c["name"] for c in inspect(conn).get_columns(table)}

    def tables() -> set[str]:
        with eng.connect() as conn:
            return set(inspect(conn).get_table_names())

    eng.upgrade = upgrade          # type: ignore[attr-defined]
    eng.stamp = stamp              # type: ignore[attr-defined]
    eng.columns = columns          # type: ignore[attr-defined]
    eng.tables = tables            # type: ignore[attr-defined]
    yield eng
    eng.dispose()


def _seed_pre_integration(eng) -> None:
    """One sandbox job with both associations set, as a running deployment has."""
    now = datetime.now(timezone.utc).isoformat(" ")
    with eng.begin() as conn:
        conn.execute(text(
            "INSERT INTO users (id,email,hashed_password,role) "
            "VALUES (7,'analyst@example.test','x','analyst')"
        ))
        conn.execute(text(
            "INSERT INTO threats (id,source,artifact_type,artifact_ref,artifact_meta,title,created_at)"
            " VALUES (1,'inbox','file','ref','{}','t',:now)"
        ), {"now": now})
        conn.execute(text(
            "INSERT INTO loop_runs (id,trigger_threat_id,current_stage,status,stage_history,"
            "targeting,created_at) VALUES (3,1,'feedback','completed','[]','{}',:now)"
        ), {"now": now})
        conn.execute(text(
            "INSERT INTO sandbox_jobs (id,public_id,source,submitted_by_user_id,original_name,"
            "sha256,md5,size_bytes,mime,magic,family,extension_mismatch,status,stage,tiers,"
            "analysis,iocs,score_breakdown,rule_score,ai_score,final_score,risk_level,"
            "loop_run_id,created_at) VALUES (1,'aaaaaaaa-1111-1111-1111-111111111111','loop',7,"
            "'invoice.ps1','abc','def',146,'text/x-powershell','','script',0,'completed',"
            "'complete','{}','{}','{}','{}',100.0,25.1,70.0,'high',3,:now)"
        ), {"now": now})


def test_the_chain_builds_a_schema_that_matches_the_models(scratch):
    """`alembic check` on a freshly migrated database must find nothing.

    This is the property that lets the rest of the suite keep using
    `create_all()`: the models and the migrations describe the same schema, so a
    test that passes against the models passes against a migrated database.
    """
    scratch.upgrade("head")
    cfg = alembic_config()
    cfg.set_main_option("sqlalchemy.url", str(scratch.url))
    with scratch.begin() as conn:
        cfg.attributes["connection"] = conn
        command.check(cfg)  # raises AutogenerateDiffsDetected on drift


def test_the_baseline_is_the_pre_integration_shape(scratch):
    """0001 must NOT already contain the integration.

    If it did, there would be no revision that adds those columns, and an
    existing database could never be repaired — which is the whole reason the
    baseline was split.
    """
    scratch.upgrade(BASELINE_REVISION)
    columns = scratch.columns("sandbox_jobs")
    assert not (INTEGRATION_COLUMNS & columns), "baseline already has the integration"
    assert MOVED_COLUMNS <= columns
    assert "sandbox_job_links" not in scratch.tables()


def test_upgrading_a_pre_integration_database_adds_the_nine_missing_columns(scratch):
    """The exact failure this migration exists for."""
    scratch.upgrade(BASELINE_REVISION)
    _seed_pre_integration(scratch)
    scratch.upgrade("head")

    columns = scratch.columns("sandbox_jobs")
    assert INTEGRATION_COLUMNS <= columns
    assert not (MOVED_COLUMNS & columns), "the moved columns should be gone from the job"

    with scratch.connect() as conn:
        row = conn.execute(text(
            "SELECT final_score, risk_level, tenant_id, verdict, mitre FROM sandbox_jobs WHERE id=1"
        )).one()
    # The row survived the rebuild, and the new columns carry their defaults
    # rather than NULL in a NOT NULL column.
    assert row.final_score == pytest.approx(70.0)
    assert row.risk_level == "high"
    assert row.tenant_id == "default"
    assert row.verdict == "{}"
    assert row.mitre == "[]"


def test_the_association_moves_to_the_link_table_rather_than_being_dropped(scratch):
    """`loop_run_id` and `submitted_by_user_id` leave the job but not the database.

    The engine may not carry a foreign key into `users` or `loop_runs` — the
    standalone product has neither table — so the portal keeps the association
    on its own side of the seam. Losing it would silently orphan every job the
    awareness loop had raised.
    """
    scratch.upgrade(BASELINE_REVISION)
    _seed_pre_integration(scratch)
    scratch.upgrade("head")

    with scratch.connect() as conn:
        link = conn.execute(text(
            "SELECT job_id, loop_run_id, submitted_by_user_id FROM sandbox_job_links"
        )).one()
    assert (link.job_id, link.loop_run_id, link.submitted_by_user_id) == (1, 3, 7)


def test_a_job_with_no_association_gets_no_link_row(scratch):
    """Absence is not an error — it is a job the portal has nothing to add to."""
    scratch.upgrade(BASELINE_REVISION)
    now = datetime.now(timezone.utc).isoformat(" ")
    with scratch.begin() as conn:
        conn.execute(text(
            "INSERT INTO sandbox_jobs (id,public_id,source,original_name,sha256,md5,size_bytes,"
            "mime,magic,family,extension_mismatch,status,stage,tiers,analysis,iocs,score_breakdown,"
            "rule_score,ai_score,final_score,risk_level,created_at) VALUES (9,"
            "'cccccccc-3333-3333-3333-333333333333','upload','x.txt','a','b',1,'text/plain','',"
            "'script',0,'completed','complete','{}','{}','{}','{}',0,0,1.7,'low',:now)"
        ), {"now": now})
    scratch.upgrade("head")
    with scratch.connect() as conn:
        assert conn.execute(text("SELECT count(*) FROM sandbox_job_links")).scalar_one() == 0


# --- the adoption ladder ------------------------------------------------------
def test_a_create_all_database_is_stamped_at_the_revision_it_matches(scratch):
    """No `alembic_version`, but the tables are there. `upgrade head` alone would
    try to CREATE what exists and abort the boot."""
    scratch.upgrade(BASELINE_REVISION)
    with scratch.begin() as conn:
        conn.execute(text("DROP TABLE alembic_version"))
    with scratch.connect() as conn:
        assert _legacy_stamp_target(conn) == BASELINE_REVISION


def test_a_database_already_carrying_the_integration_is_stamped_at_that_revision(scratch):
    """Stamping it at the baseline would re-run 0002 and re-add existing columns."""
    scratch.upgrade("head")
    with scratch.begin() as conn:
        conn.execute(text("DROP TABLE alembic_version"))
    with scratch.connect() as conn:
        assert _legacy_stamp_target(conn) == SANDBOX_ENGINE_REVISION


def test_an_empty_database_is_not_adopted(scratch):
    """Nothing to adopt — the migrations build it from nothing."""
    with scratch.connect() as conn:
        assert _legacy_stamp_target(conn) is None


def test_a_database_alembic_already_manages_is_not_re_stamped(scratch):
    scratch.upgrade("head")
    with scratch.connect() as conn:
        assert _legacy_stamp_target(conn) is None


def test_an_undatable_database_is_refused_rather_than_guessed_at(scratch):
    """Tables, but nothing to date them by.

    Stamping a revision that does not match tells Alembic a migration has run
    when it has not, and the next upgrade then alters columns that are not
    there — corruption rather than a clean failure. Refusing is the only safe
    answer, and it names what it found.
    """
    with scratch.begin() as conn:
        conn.execute(text("CREATE TABLE something_else (id INTEGER PRIMARY KEY)"))
    with scratch.connect() as conn:
        with pytest.raises(UnadoptableDatabase) as caught:
            _legacy_stamp_target(conn)
    assert "something_else" in str(caught.value)


def test_the_ladder_covers_every_revision_that_touches_sandbox_jobs():
    """A migration that adds a column without adding a rung is a boot failure.

    The pre-Alembic database gets stamped too low, the next upgrade re-adds a
    column that already exists, and the service does not come up. Nothing else
    catches this, because a fresh database never walks that path.
    """
    from app.database import _ADOPTION_LADDER

    revisions = {rev for rev, _markers in _ADOPTION_LADDER}
    versions_dir = alembic_config().get_main_option("script_location")
    assert versions_dir  # sanity: config resolved

    import pathlib

    files = list((pathlib.Path(versions_dir) / "versions").glob("*.py"))
    touching = set()
    for path in files:
        text_ = path.read_text(encoding="utf-8")
        rev = None
        for line in text_.splitlines():
            if line.startswith("revision = "):
                rev = line.split("=", 1)[1].strip().strip('"\'')
                break
        if rev and rev != BASELINE_REVISION and "sandbox_jobs" in text_ and "add_column" in text_:
            touching.add(rev)
    missing = touching - revisions
    assert not missing, (
        f"revisions add columns to sandbox_jobs but have no rung in _ADOPTION_LADDER: {missing}"
    )
