import { useEffect, useRef, useState } from 'react'
import { Link } from 'react-router-dom'
import {
  ArrowRight,
  Award,
  CheckCircle2,
  ChevronDown,
  Eye,
  Flame,
  GraduationCap,
  HelpCircle,
  Lock,
  Megaphone,
  PlayCircle,
  ScanEye,
  ShieldCheck,
  Target,
  Trophy,
  Users,
  X,
  type LucideIcon,
} from 'lucide-react'
import { api } from '../../lib/api'
import { usePoll } from '../../lib/usePoll'
import { useEscape } from '../../lib/useEscape'
import { Tour, hasSeenTour, type TourStep } from '../../components/Tour'
import type {
  AssignmentDetail,
  Badge as BadgeType,
  EmployeeDashboard,
  EmployeeDetail,
  Report,
} from '../../lib/types'
import {
  Badge,
  Button,
  Card,
  LoadState,
  Modal,
  SectionTitle,
  Skeleton,
  ThreatOriginChip,
  channelLabel,
  cx,
  riskTone,
  timeAgo,
} from '../../components/ui'

const PORTAL_TOUR_KEY = 'cyclo_tour_seen_portal'

const PORTAL_TOUR: TourStep[] = [
  {
    title: 'Your security portal',
    body: 'This is the employee side of the loop: real threats that targeted people like you become short, personal training — and completing it visibly lowers your risk score.',
  },
  {
    target: '[data-tour="me-training"]',
    title: 'Training made from real attacks',
    body: 'Each module here was generated by AI from a real threat our sandbox analyzed — and it tells you exactly why YOU were selected for it.',
  },
  {
    target: '[data-tour="me-risk"]',
    title: 'Your risk score',
    body: 'A transparent 0–100 score. Every change is listed with its reason — training lowers it, risky clicks raise it. Watch it move when you finish a module.',
  },
  {
    target: '[data-tour="me-report"]',
    title: 'Be the sensor',
    body: 'Seen something suspicious? One click reports it. AI triages it instantly, an analyst reviews it, and it can become training for your whole team — starting from you.',
  },
]

export function EmployeePortal() {
  const { data: dash, error: dashError, status: dashStatus, refresh } = usePoll<EmployeeDashboard>(
    () => api.get('/api/dashboard/employee'),
    4000,
  )
  const { data: assignments, refresh: refreshAssignments } = usePoll<AssignmentDetail[]>(
    () => api.get('/api/training/my'),
    4000,
  )
  const { data: myReports, refresh: refreshReports } = usePoll<Report[]>(() => api.get('/api/reports/my'), 6000)
  const { data: me } = usePoll<EmployeeDetail>(() => api.get('/api/employees/me'), 10000)
  const [showReport, setShowReport] = useState(false)
  const [showTour, setShowTour] = useState(false)

  useEffect(() => {
    if (dash && !hasSeenTour(PORTAL_TOUR_KEY)) {
      const t = setTimeout(() => setShowTour(true), 700)
      return () => clearTimeout(t)
    }
  }, [dash])

  // Only a 403 actually means "no employee profile". Reporting a dead API or a
  // 500 with that copy sends the analyst chasing a permissions problem that
  // does not exist.
  if (!dash && dashStatus === 403) {
    return (
      <div className="fade-in py-16 text-center">
        <div className="text-3xl">🔒</div>
        <h1 className="mt-3 text-lg font-bold">This portal is for employee accounts</h1>
        <p className="mt-1 text-sm text-muted">
          Your account isn't linked to an employee profile, so there's no personal security portal to show.
        </p>
        <Link to="/" className="mt-4 inline-block text-sm text-accent hover:underline">
          ← Back to the dashboard
        </Link>
      </div>
    )
  }
  if (!dash) return <LoadState error={dashError} label="Loading your portal…" onRetry={refresh} />

  const assignmentsLoading = assignments === undefined || assignments === null
  const pending = (assignments ?? []).filter((a) => a.status === 'assigned' || a.status === 'in_progress')
  const done = (assignments ?? []).filter((a) => a.status === 'completed')
  const expired = (assignments ?? []).filter((a) => a.status === 'expired')
  // Trust the dashboard payload for the count on first paint (issue: the
  // "All caught up" flash) — the detailed list arrives a beat later.
  const pendingCount = assignmentsLoading ? dash.assignments.pending : pending.length

  return (
    <div className="fade-in space-y-5">
      {/* header */}
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div>
          <h1 className="text-xl font-bold tracking-tight">Salam, {dash.employee.name.split(' ')[0]} 👋</h1>
          <p className="text-sm text-muted">
            {dash.employee.role_title} · {dash.employee.department}
          </p>
        </div>
        <div className="flex items-center gap-2">
          <Button variant="ghost" onClick={() => setShowTour(true)}>
            <HelpCircle size={14} /> Tour
          </Button>
          <span data-tour="me-report">
            <Button onClick={() => setShowReport(true)} className="px-4 py-2 text-[15px]">
              <Megaphone size={16} /> Report suspicious
            </Button>
          </span>
        </div>
      </div>

      {/* next action strip — the page always says what to do first */}
      {pendingCount > 0 ? (
        <Link
          to={pending[0] ? `/learn/${pending[0].id}` : '#'}
          className="flex items-center gap-3 rounded-xl border border-warn/40 bg-warn/5 px-4 py-3 transition-colors hover:border-warn/70"
        >
          <span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg border border-warn/40 bg-warn/10 text-warn">
            <GraduationCap size={16} />
          </span>
          <span className="flex-1 text-sm">
            <span className="font-semibold text-warn">
              {pendingCount} training module{pendingCount > 1 ? 's' : ''} waiting for you
            </span>
            <span className="text-muted"> — built from real threats that targeted people in your role. ~3 min each.</span>
          </span>
          <span className="flex items-center gap-1 text-sm font-medium text-warn">
            Start now <ArrowRight size={15} />
          </span>
        </Link>
      ) : (
        <div className="flex items-center gap-3 rounded-xl border border-good/25 bg-good/5 px-4 py-3">
          <CheckCircle2 size={16} className="shrink-0 text-good" />
          <span className="text-sm text-muted">
            <span className="font-medium text-good">All clear.</span> No training assigned right now — keep reporting
            anything suspicious and your score stays low.
          </span>
        </div>
      )}

      {/* ROW 1 — the loop's output (hero) + the risk story */}
      <div className="grid gap-5 lg:grid-cols-3">
        {/* training hero */}
        <Card
          className={cx('p-5 lg:col-span-2', pendingCount > 0 && 'border-warn/40')}
          data-tour="me-training"
        >
          <SectionTitle
            right={
              <span className="text-[11px] text-faint">
                {pendingCount > 0 ? `${pendingCount} to complete` : 'up to date'}
              </span>
            }
          >
            Your micro-training — from real threats
          </SectionTitle>

          {assignmentsLoading ? (
            <div className="space-y-3">
              <Skeleton className="h-32" />
              <Skeleton className="h-32 opacity-60" />
            </div>
          ) : pending.length === 0 ? (
            <div className="rounded-lg border border-dashed border-border py-10 text-center">
              <ShieldCheck size={22} className="mx-auto mb-2 text-good/70" />
              <p className="text-sm font-medium text-muted">Nothing assigned — you're up to date. 🎉</p>
              <p className="mx-auto mt-1 max-w-sm text-xs text-faint">
                When a real threat targets your role or department, the loop turns it into a short module and it appears
                here — with the reason you were selected.
              </p>
            </div>
          ) : (
            <div className="space-y-3">
              {pending.map((a) => (
                <PendingTrainingCard key={a.id} assignment={a} />
              ))}
            </div>
          )}

          {(done.length > 0 || expired.length > 0) && (
            <div className="mt-5 border-t border-border pt-4">
              <SectionTitle
                right={
                  dash.assignments.avg_score !== null ? (
                    <span className="text-[11px] text-faint">
                      avg quiz score <span className="font-semibold text-accent">{dash.assignments.avg_score.toFixed(0)}%</span>
                    </span>
                  ) : undefined
                }
              >
                Completed
              </SectionTitle>
              <div className="space-y-1.5">
                {done.map((a) => (
                  <Link
                    key={a.id}
                    to={`/learn/${a.id}`}
                    className="flex items-center gap-3 rounded-lg bg-surface-2 px-3 py-2 text-xs transition-colors hover:bg-surface-3"
                  >
                    <CheckCircle2 size={13} className={cx('shrink-0', (a.score ?? 0) >= 60 ? 'text-good' : 'text-warn')} />
                    <span className="flex-1 truncate font-medium">{a.module.title}</span>
                    <span className={cx('font-mono font-bold tabular-nums', (a.score ?? 0) >= 60 ? 'text-good' : 'text-warn')}>
                      {a.score?.toFixed(0)}%
                    </span>
                    <span className="text-faint">{a.completed_at ? timeAgo(a.completed_at) : ''}</span>
                    <span className="text-accent">Review →</span>
                  </Link>
                ))}
                {expired.map((a) => (
                  <div key={a.id} className="flex items-center gap-3 rounded-lg bg-surface-2 px-3 py-2 text-xs" title="Expired training raises your risk score — complete modules before the loop is measured.">
                    <X size={13} className="shrink-0 text-bad" />
                    <span className="flex-1 truncate font-medium text-muted">{a.module.title}</span>
                    <Badge value="expired" />
                    <span className="text-faint">raised your risk +4</span>
                  </div>
                ))}
              </div>
            </div>
          )}
        </Card>

        {/* risk story rail */}
        <Card className="p-5" data-tour="me-risk">
          <SectionTitle>Your risk score</SectionTitle>
          <div className="flex items-center justify-center">
            <RiskDial score={dash.employee.risk_score} />
          </div>
          {/* human scale */}
          <div className="mt-1 flex items-center justify-center gap-3 text-[10px] text-faint">
            <span className="flex items-center gap-1"><span className="h-1.5 w-1.5 rounded-full bg-good" /> 0–39 low</span>
            <span className="flex items-center gap-1"><span className="h-1.5 w-1.5 rounded-full bg-warn" /> 40–59 elevated</span>
            <span className="flex items-center gap-1"><span className="h-1.5 w-1.5 rounded-full bg-bad" /> 60+ high</span>
          </div>
          <p className="mt-2 text-center text-xs text-muted">
            {dash.employee.risk_score < 40
              ? 'Attackers would have a hard time with you. Keep it up.'
              : dash.employee.risk_score < 60
                ? 'Some signals need attention — completing training brings this down fast.'
                : 'You are a likely target right now — the modules above are your fastest way down.'}
          </p>

          {me && me.recent_events.length >= 2 && (
            <div className="mt-4">
              <div className="mb-1 flex items-baseline justify-between">
                <span className="text-[10px] font-semibold uppercase tracking-[0.12em] text-faint">Your trend</span>
                <span className="text-[10px] text-faint">last {Math.min(me.recent_events.length, 15)} events</span>
              </div>
              <RiskSparkline currentScore={me.current_risk_score} events={me.recent_events} />
            </div>
          )}

          <div className="mt-4 border-t border-border pt-3">
            <div className="mb-1.5 text-[10px] font-semibold uppercase tracking-[0.12em] text-faint">
              What moved it recently
            </div>
            <div className="space-y-1">
              {(me?.recent_events ?? []).slice(0, 4).map((e) => (
                <div key={e.id} className="flex items-center gap-2 text-[11px]">
                  <span className={cx('w-10 shrink-0 text-right font-mono font-semibold tabular-nums', e.delta > 0 ? 'text-bad' : 'text-good')}>
                    {e.delta > 0 ? '+' : ''}{e.delta.toFixed(1)}
                  </span>
                  <span className="truncate text-muted">{e.reason}</span>
                </div>
              ))}
              {(!me || me.recent_events.length === 0) && (
                <p className="text-[11px] text-faint">No events yet — your score is at its baseline.</p>
              )}
            </div>
          </div>
        </Card>
      </div>

      {/* ROW 2 — engagement layer (deliberately demoted) */}
      <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">
        {/* scorecard */}
        <Card className="p-5">
          <SectionTitle>Your scorecard</SectionTitle>
          <div className="grid grid-cols-2 gap-2 text-center">
            <MiniStat icon={Award} tone="text-accent" value={dash.gamification.points} label="points" />
            <MiniStat icon={Flame} tone={dash.gamification.streak > 0 ? 'text-warn' : 'text-faint'} value={dash.gamification.streak} label="streak" />
            <MiniStat icon={Megaphone} tone="text-indigo" value={dash.gamification.reports_submitted} label="reports" />
            <MiniStat
              icon={GraduationCap}
              tone="text-good"
              value={dash.assignments.avg_score !== null ? `${dash.assignments.avg_score.toFixed(0)}%` : '—'}
              label="avg quiz"
            />
          </div>
          {dash.gamification.rank && (
            <p className="mt-3 text-center text-xs text-muted">
              You're <span className="font-bold text-accent">#{dash.gamification.rank}</span> company-wide
            </p>
          )}
        </Card>

        {/* achievements */}
        <Card className="p-5">
          <SectionTitle
            right={
              <span className="text-[11px] text-faint">
                {dash.gamification.badges.filter((b) => b.earned).length}/{dash.gamification.badges.length}
              </span>
            }
          >
            Achievements
          </SectionTitle>
          <div className="grid grid-cols-2 gap-2 sm:grid-cols-3">
            {dash.gamification.badges.map((b) => (
              <BadgeTile key={b.id} badge={b} />
            ))}
          </div>
        </Card>

        {/* standings */}
        <Card className="p-5 md:col-span-2 xl:col-span-1">
          <SectionTitle>
            <span className="flex items-center gap-1.5">
              <Trophy size={13} className="text-warn" /> Standings
            </span>
          </SectionTitle>
          <div className="space-y-1">
            {dash.gamification.leaderboard.slice(0, 5).map((row, i) => (
              <LeaderRow key={row.employee_id} rank={i + 1} name={row.name} value={row.points} mine={row.employee_id === dash.employee.id} />
            ))}
            {/* always show YOUR row, even outside the top 5 */}
            {dash.gamification.rank && dash.gamification.rank > 5 && (
              <>
                <div className="py-0.5 text-center text-[10px] text-faint">···</div>
                <LeaderRow rank={dash.gamification.rank} name={dash.employee.name} value={dash.gamification.points} mine />
              </>
            )}
            {!dash.gamification.rank && (
              <p className="rounded-lg bg-surface-2 px-2.5 py-2 text-[11px] text-faint">
                Complete your first module to enter the leaderboard.
              </p>
            )}
          </div>
          <div className="mt-3 border-t border-border pt-3">
            <div className="mb-1.5 flex items-center gap-1.5 text-[10px] font-semibold uppercase tracking-[0.12em] text-faint">
              <Users size={11} /> Team standings <span className="normal-case tracking-normal">(safest first)</span>
            </div>
            <div className="space-y-1">
              {dash.gamification.team_leaderboard.slice(0, 4).map((t, i) => (
                <LeaderRow key={t.department_id} rank={i + 1} name={t.name} value={t.avg_risk.toFixed(0)} mine={t.is_mine} />
              ))}
            </div>
          </div>
        </Card>
      </div>

      {/* reports — the human sensor, with the AI verdict paid off */}
      <Card className="p-5">
        <SectionTitle right={<span className="text-[11px] text-faint">AI-triaged instantly · reviewed by an analyst</span>}>
          Your reports
        </SectionTitle>
        {!myReports || myReports.length === 0 ? (
          <div className="rounded-lg border border-dashed border-border py-8 text-center text-sm text-faint">
            Seen something odd? Hit <span className="text-accent">Report suspicious</span> — the AI triages it on the
            spot and it can become training for the whole company.
          </div>
        ) : (
          <div className="space-y-1.5">
            {myReports.map((r) => (
              <ReportRow key={r.id} report={r} />
            ))}
          </div>
        )}
      </Card>

      {showReport && (
        <ReportModal
          onClose={() => setShowReport(false)}
          onSubmitted={() => {
            setShowReport(false)
            void refresh()
            void refreshReports()
            void refreshAssignments()
          }}
        />
      )}
      {showTour && <Tour steps={PORTAL_TOUR} storageKey={PORTAL_TOUR_KEY} onClose={() => setShowTour(false)} />}
    </div>
  )
}

// --- training card (pending) --------------------------------------------------

function PendingTrainingCard({ assignment: a }: { assignment: AssignmentDetail }) {
  return (
    <Link
      to={`/learn/${a.id}`}
      className="group block rounded-xl border border-warn/30 bg-warn/[0.04] p-4 transition-colors hover:border-warn/60"
    >
      {/* origin story — the loop, visible */}
      <div className="flex flex-wrap items-center gap-2">
        {a.module.ai_generated && <ThreatOriginChip source={a.module.generation_source} />}
        <Badge value={a.module.channel} label={channelLabel(a.module.channel)} />
        <span className="text-[11px] text-faint">~{a.module.est_minutes} min</span>
        <span className="ml-auto text-[11px] text-faint">{timeAgo(a.assigned_at)}</span>
      </div>

      <h3 className="mt-2 text-[15px] font-semibold leading-snug group-hover:text-warn">{a.module.title}</h3>
      <p className="mt-1 line-clamp-2 text-xs leading-relaxed text-muted">{a.module.description}</p>

      {a.targeting_reasons.length > 0 && (
        <div className="mt-2.5">
          <span className="mr-1.5 text-[10px] font-semibold uppercase tracking-wide text-indigo">Why you:</span>
          <span className="inline-flex flex-wrap gap-1.5 align-middle">
            {a.targeting_reasons.map((r) => (
              <span key={r} className="rounded-md border border-indigo/25 bg-indigo/10 px-1.5 py-0.5 text-[10px] text-indigo">
                {r}
              </span>
            ))}
          </span>
        </div>
      )}

      <div className="mt-3 flex items-center gap-1.5 text-sm font-semibold text-warn">
        <PlayCircle size={16} /> Start training
        <ArrowRight size={14} className="transition-transform group-hover:translate-x-0.5" />
      </div>
    </Link>
  )
}

// --- risk dial + sparkline ------------------------------------------------------

function useAnimatedNumber(target: number, durationMs = 700): number {
  const [value, setValue] = useState(target)
  const fromRef = useRef(target)
  useEffect(() => {
    const from = fromRef.current
    if (from === target) return
    let raf = 0
    const start = performance.now()
    const tick = (now: number) => {
      const t = Math.min(1, (now - start) / durationMs)
      const eased = 1 - Math.pow(1 - t, 3)
      setValue(from + (target - from) * eased)
      if (t < 1) raf = requestAnimationFrame(tick)
      else fromRef.current = target
    }
    raf = requestAnimationFrame(tick)
    return () => cancelAnimationFrame(raf)
  }, [target, durationMs])
  return value
}

function RiskDial({ score }: { score: number }) {
  const animated = useAnimatedNumber(score)
  const tone = riskTone(animated)
  const color = animated >= 60 ? 'var(--color-bad)' : animated >= 40 ? 'var(--color-warn)' : 'var(--color-good)'
  const radius = 56
  const circumference = 2 * Math.PI * radius
  const arc = (270 / 360) * circumference
  const filled = (Math.min(100, Math.max(0, animated)) / 100) * arc
  return (
    <svg viewBox="0 0 140 140" className="h-36 w-36" role="img" aria-label={`Risk score ${score.toFixed(0)} out of 100`}>
      <g transform="rotate(135 70 70)">
        <circle cx="70" cy="70" r={radius} fill="none" stroke="var(--color-surface-3)" strokeWidth="10"
          strokeDasharray={`${arc} ${circumference}`} strokeLinecap="round" />
        <circle cx="70" cy="70" r={radius} fill="none" style={{ stroke: color }} strokeWidth="10"
          strokeDasharray={`${filled} ${circumference}`} strokeLinecap="round" />
      </g>
      <text x="70" y="66" textAnchor="middle" style={{ fill: color }} fontSize="30" fontWeight="700">
        {animated.toFixed(0)}
      </text>
      <text x="70" y="86" textAnchor="middle" fill="var(--color-muted)" fontSize="10">
        {tone.label} risk
      </text>
    </svg>
  )
}

function RiskSparkline({ currentScore, events }: { currentScore: number; events: EmployeeDetail['recent_events'] }) {
  // events arrive newest-first; walk backwards to reconstruct the score path.
  const recent = events.slice(0, 15)
  const scores: number[] = [currentScore]
  for (const e of recent) {
    scores.push(Math.max(0, Math.min(100, scores[scores.length - 1] - e.delta)))
  }
  scores.reverse() // oldest → newest, ending at the current score
  const w = 260
  const h = 44
  const min = Math.min(...scores)
  const max = Math.max(...scores)
  const span = Math.max(6, max - min)
  const pts = scores.map((s, i) => {
    const x = (i / (scores.length - 1)) * (w - 4) + 2
    const y = h - 4 - ((s - (min - 2)) / span) * (h - 10)
    return `${x.toFixed(1)},${y.toFixed(1)}`
  })
  const improving = scores[scores.length - 1] <= scores[0]
  const stroke = improving ? 'var(--color-good)' : 'var(--color-bad)'
  return (
    <div className="flex items-center gap-2">
      <svg viewBox={`0 0 ${w} ${h}`} className="h-11 w-full" preserveAspectRatio="none">
        <polyline points={pts.join(' ')} fill="none" style={{ stroke }} strokeWidth="2" strokeLinejoin="round" strokeLinecap="round" opacity="0.9" />
        <circle cx={pts[pts.length - 1].split(',')[0]} cy={pts[pts.length - 1].split(',')[1]} r="2.5" style={{ fill: stroke }} />
      </svg>
      <span className={cx('shrink-0 text-[10px] font-semibold', improving ? 'text-good' : 'text-bad')}>
        {improving ? '↓ improving' : '↑ rising'}
      </span>
    </div>
  )
}

// --- small pieces -----------------------------------------------------------------

function MiniStat({ icon: Icon, tone, value, label }: { icon: LucideIcon; tone: string; value: number | string; label: string }) {
  return (
    <div className="rounded-lg border border-border bg-surface-2 p-3">
      <Icon size={15} className={cx('mx-auto', tone)} />
      <div className="mt-1 text-lg font-bold tabular-nums">{value}</div>
      <div className="text-[10px] text-faint">{label}</div>
    </div>
  )
}

function LeaderRow({ rank, name, value, mine }: { rank: number; name: string; value: number | string; mine?: boolean }) {
  return (
    <div className={cx('flex items-center gap-2 rounded-lg px-2.5 py-1.5 text-[13px]', mine ? 'bg-accent/10 text-accent' : 'text-muted')}>
      <span className="w-5 shrink-0 text-xs font-bold">{rank}</span>
      <span className="flex-1 truncate">{name}{mine ? ' (you)' : ''}</span>
      <span className="font-mono text-xs font-semibold tabular-nums">{value}</span>
    </div>
  )
}

const BADGE_ICONS: Record<string, LucideIcon> = { Eye, ScanEye, Target, Flame, GraduationCap, ShieldCheck }

function BadgeTile({ badge }: { badge: BadgeType }) {
  const Icon = BADGE_ICONS[badge.icon] ?? Award
  return (
    <div
      className={cx(
        'flex min-h-[118px] flex-col items-center rounded-xl border p-2.5 text-center',
        badge.earned ? 'border-accent/40 bg-accent/5' : 'border-border bg-surface-2',
      )}
      title={badge.description}
    >
      <div
        className={cx(
          'flex h-9 w-9 shrink-0 items-center justify-center rounded-full border',
          badge.earned ? 'border-accent/50 bg-accent/10 text-accent' : 'border-border-2 bg-surface-3 text-faint',
        )}
      >
        {badge.earned ? <Icon size={17} /> : <Lock size={14} />}
      </div>
      <div className={cx('mt-1.5 text-[11px] font-semibold leading-tight', badge.earned ? 'text-ink' : 'text-muted')}>
        {badge.name}
      </div>
      <div className="mt-0.5 line-clamp-2 flex-1 text-[10px] leading-tight text-muted">{badge.description}</div>
      {/* progress bar slot is always reserved so the grid rows stay aligned */}
      <div className="mt-1.5 h-1 w-full overflow-hidden rounded-full bg-surface-3">
        <div
          className={cx('h-full rounded-full', badge.earned ? 'bg-accent' : 'bg-indigo')}
          style={{ width: `${(badge.earned ? 1 : badge.progress) * 100}%` }}
        />
      </div>
    </div>
  )
}

// --- reports: expandable rows with the AI verdict paid off -------------------------

function reportStory(r: Report): { text: string; tone: string } {
  if (r.status === 'in_loop')
    return {
      text: r.linked_loop_run_id
        ? 'Your report started a response loop — training was generated from it. You protected the whole team.'
        : 'Your report is in the response loop.',
      tone: 'text-accent',
    }
  if (r.status === 'dismissed')
    return { text: 'Reviewed — it turned out to be safe. Still exactly the right call to report it.', tone: 'text-muted' }
  return { text: 'An analyst is reviewing this now.', tone: 'text-warn' }
}

function ReportRow({ report: r }: { report: Report }) {
  const [open, setOpen] = useState(false)
  const story = reportStory(r)
  return (
    <div className="rounded-lg border border-border bg-surface-2">
      <button onClick={() => setOpen(!open)} className="flex w-full items-center gap-3 px-3 py-2 text-left text-xs">
        <Badge value={r.artifact_type} label={channelLabel(r.artifact_type)} />
        {r.triage_summary && <Badge value={r.triage_summary.suspicion_level} label={`${r.triage_summary.suspicion_level}`} />}
        <span className="flex-1 truncate text-muted">{r.artifact_ref.slice(0, 70)}…</span>
        <span className={cx('hidden shrink-0 sm:inline', story.tone)}>{story.text.split('—')[0].trim()}</span>
        <span className="shrink-0 text-faint">{timeAgo(r.created_at)}</span>
        <ChevronDown size={13} className={cx('shrink-0 text-faint transition-transform', open && 'rotate-180')} />
      </button>
      {open && (
        <div className="border-t border-border px-3 py-2.5 text-xs fade-in">
          <p className={cx('font-medium', story.tone)}>{story.text}</p>
          {r.triage_summary && (
            <div className="mt-2 rounded-lg border border-indigo/20 bg-indigo/5 p-2.5">
              <div className="text-[10px] font-semibold uppercase tracking-wide text-indigo">AI triage verdict</div>
              <p className="mt-1 leading-relaxed text-muted">{r.triage_summary.summary}</p>
              {r.triage_summary.indicators.length > 0 && (
                <div className="mt-1.5 flex flex-wrap gap-1">
                  {r.triage_summary.indicators.map((ind) => (
                    <span key={ind} className="rounded border border-warn/25 bg-warn/10 px-1.5 py-0.5 text-[10px] text-warn">
                      {ind}
                    </span>
                  ))}
                </div>
              )}
            </div>
          )}
        </div>
      )}
    </div>
  )
}

// --- report modal ------------------------------------------------------------------

const REPORT_TYPES = [
  { value: 'email', label: 'Email' },
  { value: 'sms', label: 'SMS / text' },
  { value: 'qr', label: 'QR code' },
  { value: 'chat', label: 'Chat (Teams/Slack)' },
  { value: 'url', label: 'Website / link' },
  { value: 'file', label: 'File / attachment' },
]

function ReportModal({ onClose, onSubmitted }: { onClose: () => void; onSubmitted: () => void }) {
  const [artifactType, setArtifactType] = useState('email')
  const [content, setContent] = useState('')
  const [note, setNote] = useState('')
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [created, setCreated] = useState<Report | null>(null)
  useEscape(created ? onSubmitted : onClose)

  const submit = async () => {
    setBusy(true)
    setError(null)
    try {
      const report = await api.post<Report>('/api/reports', {
        artifact_type: artifactType,
        artifact_ref: content,
        note,
      })
      setCreated(report)
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Failed to submit')
    } finally {
      setBusy(false)
    }
  }

  return (
    <Modal
      title={created ? 'Report received' : 'Report something suspicious'}
      onClose={created ? onSubmitted : onClose}
      hideHeader={!!created}
    >
        {created ? (
          /* success — pay off the AI moment instead of a disappearing sticker */
          <div className="fade-in">
            <div className="text-center">
              <div className="text-3xl">🛡️</div>
              <h3 className="mt-2 text-lg font-semibold text-good">Report received — you're the sensor</h3>
              <p className="mt-1 text-sm text-muted">
                The AI triaged it instantly; an analyst will review it next. Reporting like this is what keeps your risk
                score low.
              </p>
            </div>
            {created.triage_summary && (
              <div className="mt-4 rounded-xl border border-indigo/25 bg-indigo/5 p-3.5 text-left">
                <div className="flex items-center gap-2">
                  <span className="text-[10px] font-semibold uppercase tracking-wide text-indigo">AI triage verdict</span>
                  <Badge value={created.triage_summary.suspicion_level} label={`${created.triage_summary.suspicion_level} suspicion`} />
                </div>
                <p className="mt-1.5 text-[13px] leading-relaxed">{created.triage_summary.summary}</p>
                {created.triage_summary.indicators.length > 0 && (
                  <div className="mt-2 flex flex-wrap gap-1.5">
                    {created.triage_summary.indicators.map((ind) => (
                      <span key={ind} className="rounded-md border border-warn/25 bg-warn/10 px-1.5 py-0.5 text-[10px] text-warn">
                        {ind}
                      </span>
                    ))}
                  </div>
                )}
              </div>
            )}
            <div className="mt-4 flex justify-center">
              <Button onClick={onSubmitted} className="px-6">Done</Button>
            </div>
          </div>
        ) : (
          <>
            <div className="space-y-3">
              <div className="flex flex-wrap gap-1.5">
                {REPORT_TYPES.map((t) => (
                  <button
                    key={t.value}
                    onClick={() => setArtifactType(t.value)}
                    className={cx(
                      'rounded-lg border px-2.5 py-1 text-xs transition-colors',
                      artifactType === t.value
                        ? 'border-accent/60 bg-accent/10 text-accent'
                        : 'border-border bg-surface-2 text-muted hover:border-border-2',
                    )}
                  >
                    {t.label}
                  </button>
                ))}
              </div>
              <textarea
                value={content}
                onChange={(e) => setContent(e.target.value)}
                rows={6}
                placeholder="Paste the message, link or describe what you saw…"
                className="w-full resize-y rounded-lg border border-border bg-surface-2 px-3 py-2 font-mono text-xs outline-none placeholder:text-faint focus:border-accent/60"
              />
              <input
                value={note}
                onChange={(e) => setNote(e.target.value)}
                placeholder="Anything else? (optional)"
                className="w-full rounded-lg border border-border bg-surface-2 px-3 py-2 text-sm outline-none placeholder:text-faint focus:border-accent/60"
              />
              {error && <div className="text-xs text-bad">{error}</div>}
              <div className="flex justify-end gap-2">
                <Button variant="ghost" onClick={onClose}>Cancel</Button>
                <Button onClick={() => void submit()} busy={busy} disabled={!content.trim()}>
                  <Megaphone size={14} /> Submit report
                </Button>
              </div>
            </div>
          </>
        )}
    </Modal>
  )
}
