"""baseline

Revision ID: 0001_baseline
Revises: 
Create Date: 2026-08-02 23:54:32.185083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_baseline'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_email', sa.String(length=255), nullable=False),
    sa.Column('actor_role', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('object_type', sa.String(length=40), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('object_label', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_actor_email'), ['actor_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_object_type'), ['object_type'], unique=False)

    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('feed_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('threat_type', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('source_name', sa.String(length=120), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('iocs', sa.JSON(), nullable=False),
    sa.Column('artifact_example', sa.Text(), nullable=False),
    sa.Column('artifact_type', sa.String(length=20), nullable=False),
    sa.Column('pushed_to_loop', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('config_summary', sa.JSON(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_status', sa.String(length=16), nullable=False),
    sa.Column('last_sync_error', sa.Text(), nullable=True),
    sa.Column('courses_imported', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integrations_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_integrations_status'), ['status'], unique=False)

    op.create_table('intel_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=60), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('source_name', sa.String(length=120), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('intel_type', sa.String(length=24), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('cvss_vector', sa.String(length=120), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('affected_products', sa.JSON(), nullable=False),
    sa.Column('mitre_techniques', sa.JSON(), nullable=False),
    sa.Column('iocs', sa.JSON(), nullable=False),
    sa.Column('reference_urls', sa.JSON(), nullable=False),
    sa.Column('relevance', sa.String(length=20), nullable=False),
    sa.Column('relevance_reason', sa.Text(), nullable=False),
    sa.Column('dismissed_by', sa.String(length=255), nullable=True),
    sa.Column('dismissed_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('intel_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_intel_items_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_intel_items_intel_type'), ['intel_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_intel_items_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_intel_items_relevance'), ['relevance'], unique=False)
        batch_op.create_index(batch_op.f('ix_intel_items_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_intel_items_source'), ['source'], unique=False)

    op.create_table('metric_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('phishing_click_rate', sa.Float(), nullable=True),
    sa.Column('report_rate', sa.Float(), nullable=True),
    sa.Column('avg_risk_score', sa.Float(), nullable=True),
    sa.Column('training_completion_rate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('metric_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metric_snapshots_date'), ['date'], unique=False)

    op.create_table('policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('policy_type', sa.String(length=32), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('owner_name', sa.String(length=120), nullable=False),
    sa.Column('owner_email', sa.String(length=255), nullable=False),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applicable_departments', sa.JSON(), nullable=False),
    sa.Column('source_filename', sa.String(length=512), nullable=False),
    sa.Column('source_mime', sa.String(length=128), nullable=False),
    sa.Column('source_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.String(length=255), nullable=False),
    sa.Column('extraction_status', sa.String(length=20), nullable=False),
    sa.Column('extraction_error', sa.Text(), nullable=True),
    sa.Column('extraction_source', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policies_extraction_status'), ['extraction_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_policies_policy_type'), ['policy_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_policies_status'), ['status'], unique=False)

    op.create_table('sandbox_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('submitted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('original_name', sa.String(length=512), nullable=False),
    sa.Column('submitted_url', sa.Text(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('md5', sa.String(length=32), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('mime', sa.String(length=128), nullable=False),
    sa.Column('magic', sa.String(length=255), nullable=False),
    sa.Column('family', sa.String(length=32), nullable=False),
    sa.Column('extension_mismatch', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('tiers', sa.JSON(), nullable=False),
    sa.Column('analysis', sa.JSON(), nullable=False),
    sa.Column('iocs', sa.JSON(), nullable=False),
    sa.Column('score_breakdown', sa.JSON(), nullable=False),
    sa.Column('rule_score', sa.Float(), nullable=False),
    sa.Column('ai_score', sa.Float(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('feedback', sa.String(length=24), nullable=True),
    sa.Column('feedback_note', sa.Text(), nullable=True),
    sa.Column('parent_job_id', sa.Integer(), nullable=True),
    sa.Column('archive_path', sa.Text(), nullable=True),
    sa.Column('loop_run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['loop_run_id'], ['loop_runs.id'], ),
    sa.ForeignKeyConstraint(['parent_job_id'], ['sandbox_jobs.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sandbox_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sandbox_jobs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sandbox_jobs_parent_job_id'), ['parent_job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sandbox_jobs_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_sandbox_jobs_risk_level'), ['risk_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_sandbox_jobs_sha256'), ['sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_sandbox_jobs_loop_run_id'), ['loop_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sandbox_jobs_status'), ['status'], unique=False)

    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('role_title', sa.String(length=120), nullable=False),
    sa.Column('role_sensitivity', sa.Float(), nullable=False),
    sa.Column('current_risk_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('manager_employee_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['manager_employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_status'), ['status'], unique=False)

    op.create_table('external_courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('integration_id', sa.Integer(), nullable=False),
    sa.Column('external_ref', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('provider_name', sa.String(length=120), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('topics', sa.JSON(), nullable=False),
    sa.Column('mapped_behaviors', sa.JSON(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('external_courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_external_courses_external_ref'), ['external_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_courses_integration_id'), ['integration_id'], unique=False)

    op.create_table('incident_risks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('incident_ref', sa.String(length=60), nullable=False),
    sa.Column('risk_type', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('confidentiality', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('affected_department_id', sa.Integer(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('required_action', sa.Text(), nullable=False),
    sa.Column('requires_training', sa.Boolean(), nullable=False),
    sa.Column('requires_quiz', sa.Boolean(), nullable=False),
    sa.Column('requires_sandbox', sa.Boolean(), nullable=False),
    sa.Column('min_score', sa.Integer(), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approver_name', sa.String(length=120), nullable=False),
    sa.Column('closure_criteria', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closure_note', sa.Text(), nullable=True),
    sa.Column('reopened_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['affected_department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incident_risks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incident_risks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_risks_incident_ref'), ['incident_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_risks_risk_type'), ['risk_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_risks_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_risks_status'), ['status'], unique=False)

    op.create_table('policy_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('rule_key', sa.String(length=120), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('rule_type', sa.String(length=20), nullable=False),
    sa.Column('technology', sa.String(length=120), nullable=False),
    sa.Column('version_spec', sa.String(length=60), nullable=False),
    sa.Column('evidence_quote', sa.Text(), nullable=False),
    sa.Column('evidence_location', sa.String(length=120), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.String(length=255), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('policy_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policy_rules_policy_id'), ['policy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_rules_rule_key'), ['rule_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_rules_status'), ['status'], unique=False)

    op.create_table('policy_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('changed_by', sa.String(length=255), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=False),
    sa.Column('diff', sa.JSON(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('policy_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policy_versions_policy_id'), ['policy_id'], unique=False)

    op.create_table('policy_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finding_type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=True),
    sa.Column('policy_rule_id', sa.Integer(), nullable=True),
    sa.Column('technology', sa.String(length=120), nullable=False),
    sa.Column('affected_version', sa.String(length=60), nullable=False),
    sa.Column('approved_version', sa.String(length=60), nullable=False),
    sa.Column('recommended_version', sa.String(length=60), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('source_ref', sa.String(length=255), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('affected_department_ids', sa.JSON(), nullable=False),
    sa.Column('affected_employee_ids', sa.JSON(), nullable=False),
    sa.Column('suggested_remediation', sa.Text(), nullable=False),
    sa.Column('required_training', sa.Text(), nullable=False),
    sa.Column('owner_name', sa.String(length=120), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.String(length=255), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.ForeignKeyConstraint(['policy_rule_id'], ['policy_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('policy_findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policy_findings_detected_at'), ['detected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_findings_finding_type'), ['finding_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_findings_policy_id'), ['policy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_findings_policy_rule_id'), ['policy_rule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_findings_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_findings_status'), ['status'], unique=False)

    op.create_table('threats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('artifact_type', sa.String(length=20), nullable=False),
    sa.Column('artifact_ref', sa.Text(), nullable=False),
    sa.Column('artifact_meta', sa.JSON(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('verdict', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('threat_type', sa.String(length=30), nullable=True),
    sa.Column('iocs', sa.JSON(), nullable=True),
    sa.Column('behavior_summary', sa.Text(), nullable=True),
    sa.Column('analysis_result', sa.JSON(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('reported_by_employee_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reported_by_employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('intel_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intel_item_id', sa.Integer(), nullable=False),
    sa.Column('match_type', sa.String(length=30), nullable=False),
    sa.Column('matched_policy_id', sa.Integer(), nullable=True),
    sa.Column('matched_rule_id', sa.Integer(), nullable=True),
    sa.Column('matched_technology', sa.String(length=120), nullable=False),
    sa.Column('matched_version', sa.String(length=60), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('affected_department_ids', sa.JSON(), nullable=False),
    sa.Column('affected_employee_ids', sa.JSON(), nullable=False),
    sa.Column('created_finding_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_finding_id'], ['policy_findings.id'], ),
    sa.ForeignKeyConstraint(['intel_item_id'], ['intel_items.id'], ),
    sa.ForeignKeyConstraint(['matched_policy_id'], ['policies.id'], ),
    sa.ForeignKeyConstraint(['matched_rule_id'], ['policy_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('intel_matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_intel_matches_intel_item_id'), ['intel_item_id'], unique=False)

    op.create_table('phishing_simulations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('template_threat_id', sa.Integer(), nullable=True),
    sa.Column('lure_template_id', sa.String(length=60), nullable=True),
    sa.Column('lure_preview', sa.Text(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('launched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['template_threat_id'], ['threats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('threat_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('quiz', sa.JSON(), nullable=False),
    sa.Column('takeaway', sa.Text(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('est_minutes', sa.Integer(), nullable=False),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('generation_source', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['threat_id'], ['threats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loop_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trigger_threat_id', sa.Integer(), nullable=False),
    sa.Column('current_stage', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('stage_history', sa.JSON(), nullable=False),
    sa.Column('training_module_id', sa.Integer(), nullable=True),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('targeting', sa.JSON(), nullable=False),
    sa.Column('measure_summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['training_module_id'], ['training_modules.id'], ),
    sa.ForeignKeyConstraint(['trigger_threat_id'], ['threats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulation_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulation_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('outcome_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['simulation_id'], ['phishing_simulations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phishing_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('artifact_type', sa.String(length=20), nullable=False),
    sa.Column('artifact_ref', sa.Text(), nullable=False),
    sa.Column('artifact_meta', sa.JSON(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('triage_summary', sa.JSON(), nullable=True),
    sa.Column('linked_threat_id', sa.Integer(), nullable=True),
    sa.Column('linked_loop_run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['linked_loop_run_id'], ['loop_runs.id'], ),
    sa.ForeignKeyConstraint(['linked_threat_id'], ['threats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('delta', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('loop_run_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.String(length=120), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['loop_run_id'], ['loop_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_events_source_id'), ['source_id'], unique=False)


    op.create_table('training_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('loop_run_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('targeting_reasons', sa.JSON(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['loop_run_id'], ['loop_runs.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['training_modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incident_risk_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_risk_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=True),
    sa.Column('sandbox_job_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewer_decision', sa.String(length=20), nullable=False),
    sa.Column('reviewer_note', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=255), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['training_assignments.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['incident_risk_id'], ['incident_risks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incident_risk_subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incident_risk_subjects_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_risk_subjects_incident_risk_id'), ['incident_risk_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_risk_subjects_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incident_risk_subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incident_risk_subjects_status'))
        batch_op.drop_index(batch_op.f('ix_incident_risk_subjects_incident_risk_id'))
        batch_op.drop_index(batch_op.f('ix_incident_risk_subjects_employee_id'))

    op.drop_table('incident_risk_subjects')
    op.drop_table('training_assignments')
    with op.batch_alter_table('risk_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_events_source_id'))

    op.drop_table('risk_events')
    op.drop_table('phishing_reports')
    op.drop_table('simulation_targets')
    op.drop_table('loop_runs')
    op.drop_table('training_modules')
    op.drop_table('phishing_simulations')
    with op.batch_alter_table('intel_matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_intel_matches_intel_item_id'))

    op.drop_table('intel_matches')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('threats')
    with op.batch_alter_table('policy_findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policy_findings_status'))
        batch_op.drop_index(batch_op.f('ix_policy_findings_severity'))
        batch_op.drop_index(batch_op.f('ix_policy_findings_policy_rule_id'))
        batch_op.drop_index(batch_op.f('ix_policy_findings_policy_id'))
        batch_op.drop_index(batch_op.f('ix_policy_findings_finding_type'))
        batch_op.drop_index(batch_op.f('ix_policy_findings_detected_at'))

    op.drop_table('policy_findings')
    with op.batch_alter_table('policy_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policy_versions_policy_id'))

    op.drop_table('policy_versions')
    with op.batch_alter_table('policy_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policy_rules_status'))
        batch_op.drop_index(batch_op.f('ix_policy_rules_rule_key'))
        batch_op.drop_index(batch_op.f('ix_policy_rules_policy_id'))

    op.drop_table('policy_rules')
    with op.batch_alter_table('incident_risks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incident_risks_status'))
        batch_op.drop_index(batch_op.f('ix_incident_risks_severity'))
        batch_op.drop_index(batch_op.f('ix_incident_risks_risk_type'))
        batch_op.drop_index(batch_op.f('ix_incident_risks_incident_ref'))
        batch_op.drop_index(batch_op.f('ix_incident_risks_created_at'))

    op.drop_table('incident_risks')
    with op.batch_alter_table('external_courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_external_courses_integration_id'))
        batch_op.drop_index(batch_op.f('ix_external_courses_external_ref'))

    op.drop_table('external_courses')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_status'))

    op.drop_table('employees')
    with op.batch_alter_table('sandbox_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sandbox_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_sandbox_jobs_sha256'))
        batch_op.drop_index(batch_op.f('ix_sandbox_jobs_loop_run_id'))
        batch_op.drop_index(batch_op.f('ix_sandbox_jobs_risk_level'))
        batch_op.drop_index(batch_op.f('ix_sandbox_jobs_public_id'))
        batch_op.drop_index(batch_op.f('ix_sandbox_jobs_parent_job_id'))
        batch_op.drop_index(batch_op.f('ix_sandbox_jobs_created_at'))

    op.drop_table('sandbox_jobs')
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policies_status'))
        batch_op.drop_index(batch_op.f('ix_policies_policy_type'))
        batch_op.drop_index(batch_op.f('ix_policies_extraction_status'))

    op.drop_table('policies')
    with op.batch_alter_table('metric_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metric_snapshots_date'))

    op.drop_table('metric_snapshots')
    with op.batch_alter_table('intel_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_intel_items_source'))
        batch_op.drop_index(batch_op.f('ix_intel_items_severity'))
        batch_op.drop_index(batch_op.f('ix_intel_items_relevance'))
        batch_op.drop_index(batch_op.f('ix_intel_items_published_at'))
        batch_op.drop_index(batch_op.f('ix_intel_items_intel_type'))
        batch_op.drop_index(batch_op.f('ix_intel_items_external_id'))

    op.drop_table('intel_items')
    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integrations_status'))
        batch_op.drop_index(batch_op.f('ix_integrations_provider'))

    op.drop_table('integrations')
    op.drop_table('feed_items')
    op.drop_table('departments')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_object_type'))
        batch_op.drop_index(batch_op.f('ix_audit_events_at'))
        batch_op.drop_index(batch_op.f('ix_audit_events_actor_email'))
        batch_op.drop_index(batch_op.f('ix_audit_events_action'))

    op.drop_table('audit_events')
    # ### end Alembic commands ###
