"""Remediation Engine, Tier 1: the persisted plan and its two honest refusals.

Three tables, and the two that are not `RemediationPlan` matter as much as it does.

`remediation_coverage_gaps` records "we looked at the catalogue and nothing
covered this" — a first-class RESULT, and, accumulated, a content roadmap ranked
by how often each gap was hit.

`remediation_control_gaps` records "the person is not the vulnerability here".
MFA push-bombing is answered by number matching, not by a module; an engine that
can only produce training will produce training, so it needs somewhere to say
the fix is a control.

No column is added to an existing table, so this revision needs no rung in the
adoption ladder — `create_table` is the one thing `create_all()` also did
correctly.

Original autogenerate header: remediation engine tier 1

Revision ID: 0004_remediation
Revises: 0003_behaviour_split
Create Date: 2026-08-03 01:41:21.517364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004_remediation'
down_revision: Union[str, Sequence[str], None] = '0003_behaviour_split'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remediation_coverage_gaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('behaviour', sa.String(length=80), nullable=False),
    sa.Column('trigger_kind', sa.String(length=40), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('times_hit', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('remediation_coverage_gaps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_remediation_coverage_gaps_behaviour'), ['behaviour'], unique=False)
        batch_op.create_index(batch_op.f('ix_remediation_coverage_gaps_last_seen_at'), ['last_seen_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_remediation_coverage_gaps_trigger_kind'), ['trigger_kind'], unique=False)

    op.create_table('remediation_control_gaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trigger_kind', sa.String(length=40), nullable=False),
    sa.Column('trigger_ref', sa.String(length=120), nullable=False),
    sa.Column('recommended_control', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('remediation_control_gaps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_remediation_control_gaps_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_remediation_control_gaps_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_remediation_control_gaps_trigger_kind'), ['trigger_kind'], unique=False)

    op.create_table('remediation_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trigger_kind', sa.String(length=40), nullable=False),
    sa.Column('trigger_ref', sa.String(length=120), nullable=False),
    sa.Column('trigger_detail', sa.JSON(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_kind', sa.String(length=20), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('framing', sa.JSON(), nullable=False),
    sa.Column('assessment', sa.JSON(), nullable=False),
    sa.Column('decision', sa.JSON(), nullable=False),
    sa.Column('urgency', sa.String(length=16), nullable=False),
    sa.Column('ai_ran', sa.Boolean(), nullable=False),
    sa.Column('not_attached_reason', sa.Text(), nullable=False),
    sa.Column('validator_adjustments', sa.JSON(), nullable=False),
    sa.Column('rejection_code', sa.String(length=60), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('manager_visible', sa.Boolean(), nullable=False),
    sa.Column('learner_disclosure', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('remediation_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_remediation_plans_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_remediation_plans_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_remediation_plans_rejection_code'), ['rejection_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_remediation_plans_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_remediation_plans_trigger_kind'), ['trigger_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_remediation_plans_trigger_ref'), ['trigger_ref'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('remediation_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_remediation_plans_trigger_ref'))
        batch_op.drop_index(batch_op.f('ix_remediation_plans_trigger_kind'))
        batch_op.drop_index(batch_op.f('ix_remediation_plans_status'))
        batch_op.drop_index(batch_op.f('ix_remediation_plans_rejection_code'))
        batch_op.drop_index(batch_op.f('ix_remediation_plans_employee_id'))
        batch_op.drop_index(batch_op.f('ix_remediation_plans_created_at'))

    op.drop_table('remediation_plans')
    with op.batch_alter_table('remediation_control_gaps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_remediation_control_gaps_trigger_kind'))
        batch_op.drop_index(batch_op.f('ix_remediation_control_gaps_status'))
        batch_op.drop_index(batch_op.f('ix_remediation_control_gaps_created_at'))

    op.drop_table('remediation_control_gaps')
    with op.batch_alter_table('remediation_coverage_gaps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_remediation_coverage_gaps_trigger_kind'))
        batch_op.drop_index(batch_op.f('ix_remediation_coverage_gaps_last_seen_at'))
        batch_op.drop_index(batch_op.f('ix_remediation_coverage_gaps_behaviour'))

    op.drop_table('remediation_coverage_gaps')
    # ### end Alembic commands ###
