"""Say where a metric snapshot came from.

The executive page charted a hand-written 26-week curve from the demo seed under
the label "Live API - measured from this deployment's own records", directly
below a tile computing the same metric from real rows. Click rate read 29% and
rising in the tile and 10.8% and falling in the chart: same metric, same page,
opposite stories, both claiming to be measured.

Existing rows backfill to "seeded" rather than "measured", deliberately. Every
snapshot that predates this column was written by the seed; calling them
measured would be the exact claim this column exists to stop.

Original autogenerate header: metric snapshot provenance

Revision ID: 0005_snapshot_source
Revises: 0004_remediation
Create Date: 2026-08-03 02:03:07.869314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0005_snapshot_source'
down_revision: Union[str, Sequence[str], None] = '0004_remediation'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metric_snapshots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=16), nullable=True))

    # Backfilled as SEEDED, not measured: every row that predates this column
    # was drawn by the demo seed.
    op.execute("UPDATE metric_snapshots SET source = 'seeded' WHERE source IS NULL")

    with op.batch_alter_table('metric_snapshots', schema=None) as batch_op:
        batch_op.alter_column('source', existing_type=sa.String(length=16), nullable=False)
        batch_op.create_index(batch_op.f('ix_metric_snapshots_source'), ['source'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metric_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metric_snapshots_source'))
        batch_op.drop_column('source')

    # ### end Alembic commands ###
